# ASP.NET Core (.NET Framework)

# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  project: '**/P/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps: 
  - task: NuGetToolInstaller@1
    name: 'NuGetToolInstaller'
  
  - task: NuGetCommand@2
    displayName: 'comman'
    inputs:
      command: restore
      restoreSolution: '$(solution)'
      feedsToUse: select

  - task: DotNetCoreCLI@2
    displayName: 'test'
    inputs:
      command: test
      projects: '$(project)'
      arguments: '--configuration $(BuildConfiguration)'


